version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
    rebase-strategy: disabled
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: disabled
    groups:
      actions:
        applies-to: version-updates
        # Group official GitHub Actions updates into a single pull request.
        patterns:
          - "actions/*"
